version: "3.9"

services:
  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: eventify_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventify
    ports:
      - "5433:5432"   # Host port 5433 â†’ Container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Hasura
  hasura:
    image: hasura/graphql-engine:v2.48.0
    container_name: eventify_hasura
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/eventify?sslmode=disable
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"b7f3c29e8a4d1f92e7b1a4c3f8d9e2c5"}'

  # MinIO
  minio:
    image: minio/minio
    container_name: eventify_minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
